### ISSUE TITLE
Remove Intro Cutscenes Error on v0.8

### ISSUE THREAD

**Issue by Qroooow2Elm** [rarksy/DBDCompanion#2]
Just downloaded, whenever I try to click to click to skip intro cutscene it gives me an error saying "Couldn't Disable Intro Cutscene".

**Comment by rarksy** [comment]
dm me on discord and i'll help you fix it in the meantime before i release a fix for it

**Comment by Qroooow2Elm** [comment]
Thanks boss, I'll do it Monday, working the long weekend

Thank you,
Džiugas

**Comment by rarksy** [comment]
Closing this issue as the new version provides a reason for the failed attempt to disable the intro cutscene, if you continue to have issues pm me on discord
