### ISSUE TITLE
application crashing

### ISSUE THREAD

**Issue by dwsturgeon** [rarksy/DBDCompanion#3]
no matter what i do the when i open the zip and copy it to my desktop the application crashes after about 5 seconds of being up. Not sure if the most recent update has broken something or how i can help troubleshoot this. Love the app.

**Comment by rarksy** [comment]
A change has been made to an api that DBDC uses and it just happened to be for the one thing that I don't have error checking for yet, I've already isolated and fixed the issue for the next update coming in the next few days, but as temporary fix there is a version in my discord that has the icon packager disabled ( the feature causing the crash ), so in the meantime you can download that, sorry for the inconvenience

**Comment by dwsturgeon** [comment]
Thank You!
